### ISSUE TITLE
[feature] Setup server environment

### ISSUE THREAD

**Issue by shyunlee** [codestates/pt_at_home_server#1]
### ISSUE
- Group:  server
- Type: feature
- Detail: setting project directory structure

### TODO
1. [x] 필요한 모듈 깔기
2. [x] endpoint 별로 폴더 및 파일 분기하여 구축
3. [x] Sequelize를 이용하여 DB 구축
