### ISSUE TITLE
[update] /myroutine/* 모든 기능구현 검토 후 수정

### ISSUE THREAD

**Issue by Jmwasd** [codestates/pt_at_home_server#69]
### ISSUE
- Group:   `server`
- Type: `update`
- Detail:  모든 기능구현 검토 후 accessToken으로 유저정보 확인

### TODO
1. [x] /myroutine/saveworkout 검토 후 수정
2. [x] /myroutine 검토 후 수정
3. [x] /myroutine/removeworkout 검토 후 수정
4. [x] /myroutine/createroutine 검토 후 수정
5. [x] /myroutine/deleteroutine 검토 후 수정
6. [x] /myroutine/myworkout 검토 후 수정

### Estimated time
> Pick one
